#logging:
#  pattern:
#    # ????????????
#    console: '%yellow(%d{yyyy-MM-dd HH:mm:ss}) %blue(%thread) %magenta(%-5level) %green(%-80logger) - %msg%n'
#    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n'
spring:
  profiles:
    active: dev
