spring:
  application:
    name: server-push
  boot:
    admin:
      client:
        url: http://localhost:8099


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always